"""Описания кодов из DSD.FDB образа DiagBox. Сгенерировано gen_dtc_dsd.py."""

DTC_FR = {
    'B0824': 'RDBI_RecordDataIdentifier_0E00',
    'B1011': 'Défaut de la sonde de température extérieure',
    'B1012': 'Défaut de la sonde de température extérieure',
    'B1081': "Défaut d'absence de communication avec le calculateur de climatisation",
    'B1083': 'Défaut interne calculateur',
    'B1101': 'Défaut du compresseur - Arrêt permanent',
    'B1102': 'Défaut du compresseur - Surintensité',
    'B1103': 'Défaut du compresseur - Anomalie puissance',
    'B1104': 'Défaut du compresseur - Température trop haute',
    'B1105': 'Défaut du compresseur - Perte de communication',
    'B1106': 'Défaut du compresseur - Tension trop basse',
    'B1107': 'Défaut du compresseur - Tension trop haute',
    'B1108': 'Défaut de la résistance de chauffage électrique 1',
    'B1109': 'Défaut de la résistance de chauffage électrique 2',
    'B1121': "Défaut moteur de recyclage d'air",
    'B1122': "Défaut moteur de recyclage d'air",
    'B1123': "Défaut moteur de recyclage d'air - mauvais fonctionnement",
    'B1130': 'Valeur 9C du parametre IO',
    'B1131': 'Valeur 9C du parametre IO',
    'B1200': 'Défaut information du compteur kilomètrique',
    'B1203': 'Défaut commutateur odomètre coincé',
    'B1400': 'Défaut de la ligne du coussin gonflable conducteur niveau 1',
    'B1401': 'Défaut de la ligne du coussin gonflable conducteur niveau 1',
    'B1402': 'Défaut de la ligne du coussin gonflable conducteur niveau 1',
    'B1403': 'Défaut de la ligne du coussin gonflable conducteur niveau 1',
    'B1404': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable conducteur niveau 1",
    'B1405': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable conducteur niveau 1",
    'B1410': 'Défaut de la ligne du coussin gonflable passager niveau 1',
    'B1411': 'Défaut de la ligne du coussin gonflable passager niveau 1',
    'B1412': 'Défaut de la ligne du coussin gonflable passager niveau 1',
    'B1413': 'Défaut de la ligne du coussin gonflable passager niveau 1',
    'B1414': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable passager niveau 1",
    'B1415': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable passager niveau 1",
    'B1420': 'Défaut de la ligne du coussin gonflable latéral avant droit',
    'B1421': 'Défaut de la ligne du coussin gonflable latéral avant droit',
    'B1422': 'Défaut de la ligne du coussin gonflable latéral avant droit',
    'B1423': 'Défaut de la ligne du coussin gonflable latéral avant droit',
    'B1424': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable latéral avant droit",
    'B1425': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable latéral avant droit",
    'B1426': 'Défaut de la ligne du satellite latéral 1 droit',
    'B1427': 'Défaut de la ligne du satellite latéral 1 droit',
    'B1428': 'Défaut de la ligne du satellite latéral 1 droit',
    'B1429': 'Défaut de la ligne du satellite latéral 1 droit',
    'B1430': 'Défaut de la ligne du coussin gonflable latéral avant gauche',
    'B1431': 'Défaut de la ligne du coussin gonflable latéral avant gauche',
    'B1432': 'Défaut de la ligne du coussin gonflable latéral avant gauche',
    'B1433': 'Défaut de la ligne du coussin gonflable latéral avant gauche',
    'B1434': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable latéral avant gauche",
    'B1435': "Défaut du circuit de mise à feu de l'allumeur coussin gonflable latéral avant gauche",
    'B1436': 'Défaut de la ligne du satellite latéral 1 gauche',
    'B1437': 'Défaut de la ligne du satellite latéral 1 gauche',
    'B1438': 'Défaut de la ligne du satellite latéral 1 gauche',
    'B1439': 'Défaut de la ligne du satellite latéral 1 gauche',
    'B1440': 'Défaut de la ligne du rideau coussin gonflable droit',
    'B1441': 'Défaut de la ligne du rideau coussin gonflable droit',
    'B1442': 'Défaut de la ligne du rideau coussin gonflable droit',
    'B1443': 'Défaut de la ligne du rideau coussin gonflable droit',
    'B1445': "Défaut du circuit de mise à feu de l'allumeur rideau coussin gonflable droit",
    'B1446': 'Défaut de la ligne du satellite latéral 2 droit',
    'B1447': 'Défaut de la ligne du satellite latéral 2 droit',
    'B1448': 'Défaut de la ligne du satellite latéral 2 droit',
    'B1449': 'Défaut de la ligne du satellite latéral 2 droit',
    'B1450': 'Défaut de la ligne du rideau coussin gonflable gauche',
    'B1451': 'Défaut de la ligne du rideau coussin gonflable gauche',
    'B1452': 'Défaut de la ligne du rideau coussin gonflable gauche',
    'B1453': 'Défaut de la ligne du rideau coussin gonflable gauche',
    'B1454': "Défaut du circuit de mise à feu de l'allumeur rideau coussin gonflable gauche",
    'B1455': "Défaut du circuit de mise à feu de l'allumeur rideau coussin gonflable gauche",
    'B1456': 'Défaut de la ligne du satellite latéral 2 gauche',
    'B1457': 'Défaut de la ligne du satellite latéral 2 gauche',
    'B1458': 'Défaut de la ligne du satellite latéral 2 gauche',
    'B1459': 'Défaut de la ligne du satellite latéral 2 gauche',
    'B1466': 'Défaut interne du calculateur (accéléromètre)',
    'B1467': 'Défaut interne du calculateur (accéléromètre)',
    'B1468': 'Défaut interne du calculateur (accéléromètre)',
    'B1476': 'Défaut de la tension d?alimentation',
    'B1477': 'Défaut de la tension d?alimentation',
    'B1478': 'Défaut de la tension interne du condensateur de sauvegarde',
    'B1479': 'Défaut de la tension interne du condensateur de sauvegarde',
    'B1488': 'Défaut du témoin de neutralisation du coussin gonflable passager',
    'B1489': 'Défaut du témoin de neutralisation du coussin gonflable passager',
    'B1496': 'Défaut interne du calculateur',
    'B1497': 'Défaut interne du calculateur',
    'B1498': 'Défaut interne du calculateur',
    'B1499': 'Défaut interne du calculateur airbag ou airbag déployé',
    'B1506': 'Défaut du prétensionneur conducteur',
    'B1509': 'Incompatibilité du calculateur airbag avec le véhicule',
    'B1519': 'Défaut de verrouillage du connecteur du calculateur',
    'B1547': 'Défaut du témoin de neutralisation du coussin gonflable passager',
    'B1550': 'Défaut du témoin défaut coussins gonflables et prétensionneurs',
    'B1551': 'Défaut du témoin défaut coussins gonflables et prétensionneurs',
    'B1557': 'Défaut interne du calculateur',
    'B1570': 'Défaut de la ligne du commutateur de neutralisation du coussin gonflable passager',
    'B1574': 'Défaut de la ligne du commutateur de neutralisation du coussin gonflable passager',
    'B1575': 'Défaut de la ligne du commutateur de neutralisation du coussin gonflable passager',
    'B1576': 'Défaut de la ligne du commutateur de neutralisation du coussin gonflable passager',
    'B1581': 'Incompatibilité du commutateur de neutralisation du coussin gonflable passager avec le calculateur airbag',
    'B1595': 'Défaut du satellite frontal avant droit',
    'B1596': 'Défaut du satellite frontal avant droit',
    'B1597': 'Défaut du satellite frontal avant droit',
    'B1598': 'Défaut du satellite frontal avant droit',
    'B1599': 'Défaut du satellite frontal avant gauche',
    'B1600': 'Défaut du satellite frontal avant gauche',
    'B1601': 'Défaut du satellite frontal avant gauche',
    'B1602': 'Défaut du satellite frontal avant gauche',
    'B1603': 'Défaut du prétensionneur conducteur',
    'B1604': 'Défaut du prétensionneur conducteur',
    'B1605': 'Défaut du prétensionneur conducteur',
    'B1607': "Défaut du circuit de mise à feu de l'allumeur du prétensionneur conducteur",
    'B1608': "Défaut du circuit de mise à feu de l'allumeur du prétensionneur conducteur",
    'B1609': 'Défaut du prétensionneur passager',
    'B1610': 'Défaut du prétensionneur passager',
    'B1611': 'Défaut du prétensionneur passager',
    'B1612': 'Défaut du prétensionneur passager',
    'B1613': "Défaut du circuit de mise à feu de l'allumeur du prétensionneur passager",
    'B1614': "Défaut du circuit de mise à feu de l'allumeur du prétensionneur passager",
    'B1616': 'Défaut interne du calculateur (accéléromètre)',
    'B1619': 'Défaut du prétensionneur retour de sangle conducteur',
    'B1620': 'Défaut du prétensionneur retour de sangle conducteur',
    'B1621': 'Défaut du prétensionneur retour de sangle conducteur',
    'B1622': 'Défaut du prétensionneur retour de sangle conducteur',
    'B1623': "Défaut du circuit de mise à feu de l'allumeur du prétensionneur retour de sangle conducteur",
    'B1624': "Défaut du circuit de mise à feu de l'allumeur du prétensionneur retour de sangle conducteur",
    'B1637': 'Défaut du satellite de choc latéral',
    'B1639': 'Défaut du satellite de choc latéral',
    'B1640': 'Défaut du satellite de choc latéral',
    'B1641': 'Défaut du satellite de choc arrière',
    'B1643': 'Défaut du satellite de choc arrière',
    'B1644': 'Défaut du satellite de choc arrière',
    'B1697': "Défaut de l'appel d'urgence",
    'B1698': 'Défaut interne du calculateur',
    'C1511': 'Défaut du capteur de couple principal',
    'C1512': 'Défaut du capteur de couple secondaire',
    'C1513': 'Défaut du capteur de couple secondaire',
    'C1514': 'Défaut du capteur de couple secondaire',
    'C1515': 'Défaut du capteur de couple secondaire',
    'C1521': 'Défaut du capteur de couple secondaire',
    'C1522': 'Défaut du capteur de couple secondaire',
    'C1531': 'Défaut du capteur de couple secondaire',
    'C1532': 'Défaut du capteur de couple secondaire',
    'C1533': 'Défaut du capteur de couple secondaire',
    'C1534': 'Défaut du capteur de couple secondaire',
    'C1541': 'Défaut du capteur de couple secondaire',
    'C1542': 'Défaut du capteur de couple secondaire',
    'C1607': 'Défaut du capteur de couple secondaire',
    'C1860': 'Défaut du capteur de couple secondaire',
    'C1861': 'Défaut du capteur de couple secondaire',
    'P0030': 'commande chauffage sonde à oxygène amont',
    'P0031': 'commande chauffage sonde à oxygène amont',
    'P0032': 'commande chauffage sonde à oxygène amont',
    'P0036': 'Défaut commande chauffage sonde à oxygène aval',
    'P0037': 'Défaut commande chauffage sonde à oxygène aval',
    'P0038': 'Défaut commande chauffage sonde à oxygène aval',
    'P0105': 'signal capteur pression tubulure admission cohérence',
    'P0106': 'signal capteur pression tubulure admission cohérence',
    'P0107': 'signal capteur pression tubulure admission court-circuit à la masse',
    'P0108': 'signal capteur pression tubulure admission circuit ouvert ou court-circuit au +Ï',
    'P0110': 'signal température air admission cohérence',
    'P0112': 'signal température air admission circuit ouvert ou court-circuit au +',
    'P0113': 'signal température air admission court-circuit à la masse',
    'P0115': 'signal température eau moteur cohérence',
    'P0116': 'signal température eau moteur cohérence',
    'P0117': 'signal température eau moteur circuit ouvert ou court-circuit au +Â',
    'P0118': 'signal température eau moteur court-circuit à la masse',
    'P0121': 'signal papillon motorisé, pistes 1 et 2 : cohérence',
    'P0122': 'signal papillon motorisé piste 1 : court-circuit à la masse»',
    'P0123': 'signal papillon motorisé piste 1 : circuit ouvert ou court-circuit au +Ç',
    'P0130': 'signal sonde à oxygène amont cohérence',
    'P0131': 'signal sonde à oxygène amont court-circuit à la masse',
    'P0132': 'signal sonde à oxygène amont court-circuit au plus',
    'P0133': 'signal sonde à oxygène amont vieillissement',
    'P0134': 'signal sonde à oxygène amont circuit ouvert',
    'P0135': 'commande chauffage sonde à oxygène amont',
    'P0136': 'signal sonde à oxygène aval cohérence',
    'P0137': 'signal sonde à oxygène aval court-circuit à la masse',
    'P0138': 'signal sonde à oxygène aval court-circuit au plus',
    'P0139': 'signal sonde à oxygène aval cohérence',
    'P0140': 'signal sonde à oxygène aval CO',
    'P0141': 'commande chauffage sonde à oxygène aval',
    'P0170': 'régulation de richesse',
    'P0171': 'régulation de richesse',
    'P0172': 'régulation de richesse',
    'P0196': 'signal température huile moteur cohérence',
    'P0197': 'signal température huile moteur court-circuit à la masse',
    'P0198': 'signal température huile moteur circuit ouvert ou court-circuit au +Ä',
    'P0201': 'commande injecteur N° 1 circuit ouvert',
    'P0202': 'commande injecteur N° 2 circuit ouvert',
    'P0203': 'commande injecteur N° 3 circuit ouvert',
    'P0204': 'commande injecteur N° 4 circuit ouvert',
    'P0215': 'commande relais pompe à carburant circuit ouvert°',
    'P0221': 'capteur pédale incohérence signaux 1 et 2 cohérence',
    'P0223': "signal capteur pédale d'accélérateur piste 1 circuit ouvert ou court-circuit au +",
    'P0227': "signal capteur pédale d'accélérateur piste 2 court-circuit à la masse",
    'P0228': "signal capteur pédale d'accélérateur piste 2 circuit ouvert ou court-circuit au +",
    'P0231': 'commande relais pompe à carburant court-circuit à la masse',
    'P0232': 'commande relais pompe à carburant court-circuit au plus',
    'P0261': 'commande injecteur N° 1 court-circuit à la masse°',
    'P0262': 'commande injecteur N° 1 court-circuit au plus',
    'P0264': 'commande injecteur N° 2 court-circuit à la masse°',
    'P0265': 'commande injecteur N° 2 court-circuit au plus',
    'P0267': 'commande injecteur N° 3 court-circuit à la masse°',
    'P0268': 'commande injecteur N° 3 court-circuit au plus',
    'P0270': 'commande injecteur N° 4 court-circuit à la masse°',
    'P0271': 'commande injecteur N° 4 court-circuit au plus',
    'P0300': 'ratés de combustion sur cylindres indéterminés',
    'P0301': 'ratés de combustion cylindre n° 1',
    'P0302': 'ratés de combustion cylindre n° 2',
    'P0303': 'ratés de combustion cylindre n° 3',
    'P0304': 'ratés de combustion cylindre n° 4',
    'P0313': "niveau bas carburant (ratés d'allumage)",
    'P0325': 'Défaut signal capteur de cliquetis',
    'P0327': 'signal capteur de cliquetis circuit ouvert',
    'P0328': 'signal capteur de cliquetis court-circuit au plus',
    'P0335': 'signal capteur régime moteur',
    'P0336': 'signal capteur régime moteur cohérence',
    'P0337': 'signal capteur régime moteur court-circuit à la masse',
    'P0338': 'signal capteur régime moteur circuit ouvert ou court-circuit au +',
    'P0341': "détection de phase intégrée à l'allumage cohérence",
    'P0342': "détection de phase intégrée à l'allumage court-circuit à la masse",
    'P0343': "détection de phase intégrée à l'allumage circuit ouvert ou court-circuit au +",
    'P0350': "commande bobine d'allumage",
    'P0351': "commande bobine d'allumage 1/4 court-circuit au plus",
    'P0352': "commande bobine d'allumage 2/3 court-circuit au plus",
    'P0410': 'injection air échappement',
    'P0420': 'vieillissement catalyseur',
    'P0443': 'commande électrovanne purge canister circuit ouvert',
    'P0445': 'commande électrovanne purge canister court-circuit au plus',
    'P0461': 'information niveau carburant cohérence ou niveau minimum atteintÀ',
    'P0462': 'information niveau carburant court-circuit à la masse',
    'P0463': 'information niveau carburant CO',
    'P0480': 'défaut commande groupe motoventilateur grande vitesse',
    'P0481': 'commande groupe motoventilateur petite vitesse',
    'P0485': 'fonction groupe motoventilateur cohérence',
    'P0500': 'signal capteur vitesse véhicule',
    'P0501': 'signal capteur vitesse véhicule cohérence',
    'P0512': 'Défaut démarrage et arrêt moteur piloté (DAMP)',
    'P0513': "Défaut de cohérence du code de l'antidémarrage",
    'P0530': 'information pression réfrigération',
    'P0532': 'information pression réfrigération court-circuit à la masse ou circuit ouvert',
    'P0533': 'information pression réfrigération court-circuit au plus',
    'P0550': 'signal capteur de pression direction assistée dysfonctionnement',
    'P0560': 'Tension batterie cohérence',
    'P0561': 'Tension batterie cohérence',
    'P0562': 'Tension batterie tension trop basse',
    'P0563': 'Tension batterie tension trop haute',
    'P0570': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0571': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0572': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0573': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0575': 'Défaut Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV2/LVV)Î',
    'P0590': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0591': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0592': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0593': 'Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV/LVV) cohérence',
    'P0601': 'calculateur moteur',
    'P0602': 'Défaut télécodage',
    'P0603': 'calculateur moteur',
    'P0604': 'calculateur moteur',
    'P0605': 'calculateur moteur',
    'P0606': 'calculateur moteur',
    'P0607': 'Défaut surveillance du calculateur moteur',
    'P0615': 'défaut relais de pilotage démarreur circuit ouvert',
    'P0616': 'défaut relais de pilotage démarreur court-circuit à la masse',
    'P0617': 'défaut relais de pilotage démarreur court-circuit au plus',
    'P061B': 'réveil Commandé à Distance : Défaut réveil partiel valeur reçue incorrecte',
    'P0620': 'Défaut information charge alternateur',
    'P0638': 'Défaut apprentissage position limp home papillon motorisé',
    'P0703': 'information feux de stop',
    'P0704': "défaut capteur d'embrayage",
    'P1096': 'réveil Commandé à Distance : Défaut réveil partiel valeur reçue incorrecte',
    'P1097': 'réveil Commandé à Distance : Défaut réveil partiel valeur reçue incorrecte',
    'P1098': 'réveil Commandé à Distance : Défaut réveil partiel valeur reçue incorrecte',
    'P1152': 'commande moteur papillon motorisé',
    'P1153': 'apprentissage des butées papillon motorisé échec apprentissage',
    'P1157': 'signal papillon motorisé piste 2 : court-circuit à la masse»',
    'P1158': 'signal papillon motorisé piste 2 : circuit ouvert ou court-circuit au +Ç',
    'P1161': 'défaut régulation position papillon court-circuit à la masse , court-circuit au plus , cohérenceà',
    'P1303': 'régulation de cliquetis cohérence',
    'P1313': 'Défaut niveau bas carburant (ratés d?allumage)',
    'P1329': 'butée de régulation de cliquetis cylindre 1 dépassée',
    'P1330': 'butée de régulation de cliquetis cylindre 2 dépassée',
    'P1331': 'butée de régulation de cliquetis cylindre 3 dépassée',
    'P1332': 'butée de régulation de cliquetis cylindre 4 dépassée',
    'P1336': 'ratés de combustion sur cylindres indéterminés',
    'P1337': 'ratés de combustion cylindre n° 1',
    'P1338': 'ratés de combustion cylindre n° 2',
    'P1339': 'ratés de combustion cylindre n° 3',
    'P1340': 'ratés de combustion cylindre n° 4',
    'P1526': 'information charge alternateur',
    'P1527': 'information charge alternateur court-circuit à la masse',
    'P1528': 'information charge alternateur circuit ouvert ou court-circuit au +',
    'P1529': 'information charge alternateur cohérence',
    'P1536': 'information feux de stop',
    'P160A': "Défaut de télécodage du numéro d'homologation",
    'P1613': 'défaut télécodage',
    'P1614': "information point dur pédale d'accélération circuit ouvert",
    'P161B': 'surveillance du calculateur moteur',
    'P1621': 'calculateur moteur',
    'P1622': 'calculateur moteur',
    'P1626': 'calculateur moteur',
    'P1627': 'surveillance du calculateur moteur',
    'P1632': 'surveillance du calculateur moteur',
    'P1643': "information point dur pédale d'accélération court-circuit à la masseÄ",
    'P1644': "information point dur pédale d'accélération court-circuit au plus",
    'P1645': "information point dur pédale d'accélération cohérence",
    'P1652': 'calculateur moteur',
    'P1653': 'calculateur moteur',
    'P1654': 'calculateur moteur',
    'P1664': 'surveillance du calculateur moteur',
    'P1667': 'calculateur moteur',
    'P1669': 'surveillance du calculateur moteur',
    'P1693': 'défaut démarrage et arrêt moteur piloté (DAMP)',
    'P1694': 'défaut démarrage et arrêt moteur piloté (DAMP) court-circuit à la masseÇ',
    'P1695': 'défaut démarrage et arrêt moteur piloté (DAMP) circuit ouvert ou court-circuit au +',
    'P1701': 'incohérence du rapport de boîte de vitesses',
    'P2096': 'signal sonde à oxygène amont vieillissement',
    'P2097': 'signal sonde à oxygène amont vieillissement',
    'P2100': 'commande moteur papillon motorisé',
    'P2102': 'commande moteur papillon motorisé',
    'P2103': 'Défaut Régulation Vitesse Véhicule / Limitation de Vitesse Véhicule (RVV2/LVV)Î',
    'P2112': 'signal papillon motorisé cohérence',
    'P2122': 'ecart entre consigne et valeur réelle papillon ou papillon bloqué',
    'P2123': 'ecart entre consigne et valeur réelle papillon ou papillon bloqué',
    'P2137': 'signal papillon motorisé, pistes 1 et 2 : cohérence',
    'P2176': 'apprentissage des butées papillon motorisé cohérence',
    'P2177': 'auto-adaptation de la régulation de richesse mélange trop pauvreÀ',
    'P2178': 'auto-adaptation de la régulation de richesse mélange trop riche',
    'P2191': 'auto-adaptation de la régulation de richesse mélange trop pauvreÀ',
    'P2192': 'auto-adaptation de la régulation de richesse mélange trop riche',
    'P2299': "détection pédale d'accélérateur bloquée dysfonctionnement",
    'P3010': 'signal papillon motorisé cohérence',
    'P3011': 'défaut régulation position papillon ressort de rappel inefficaceÀ',
    'P3012': "défaut régulation position papillon ressort d'ouverture inefficaceÂ",
    'P3013': 'apprentissage des butées papillon motorisé apprentissage incohérent',
    'P3014': "apprentissage des butées papillon motorisé conditions d'apprentissage non remplies",
    'P3015': 'signal papillon motorisé signal amplifié',
    'P3021': 'relais de démarrage à froid système BIO FLEX',
    'P3022': 'relais de démarrage à froid système BIO FLEX',
    'P3023': 'relais de démarrage à froid système BIO FLEX',
    'P3031': 'Défaut Régulation Vitesse Véhicule',
    'U0028': 'erreur MIL en provenance du CAN',
    'U0055': 'défaut de communication sur le CAN confort',
    'U0103': 'absence de communication avec le calculateur BVA°',
    'U0122': 'absence de communication avec le calculateur ABS/ESP',
    'U0167': 'Défaut absence de réponse du Boîtier de Servitude Intelligent à la demande de déverrouillageÜ',
    'U1003': 'absence de communication sur le CAN',
    'U1073': 'Défaut sur la ligne K',
    'U1100': 'Défaut absence de communication avec le calculateur de contrôle véhicule électrique',
    'U1101': 'Défaut absence de communication avec le calculateur TRANSMISSIONÀ',
    'U1102': "Défaut d'absence de communication avec le calculateur ABS",
    'U1106': 'Défaut absence de communication avec le calculateur de direction assistée électriqueÔ',
    'U1107': 'absence de communication avec le calculateur ABS/ESP',
    'U1108': "Défaut d'absence de communication avec le combiné",
    'U1109': "Défaut d'absence de communication avec le BSI",
    'U1120': 'Défaut information émise par le calculateur moteur',
    'U1121': 'Défaut information émise par le calculateur ENGINE',
    'U1122': 'Défaut information émise par le calculateur ABS/ESP',
    'U1126': 'Défaut information émise par le calculateur de direction assistée électrique',
    'U1128': 'Défaut du capteur de couple secondaire',
    'U1129': 'Défaut information émise par le boîtier de servitude intelligent (BSI)',
    'U1132': "Défaut de l'information émise par le calculateur de coussin gonflable",
    'U1136': 'Défaut information émise par le calculateur SMART ENTRY',
    'U1190': 'Défaut du réseau CAN',
    'U1206': 'Défaut interne au calculateur',
    'U1416': 'Défaut du capteur de couple secondaire',
    'U1432': 'Défaut du capteur de couple secondaire',
    'U1800': 'Défaut du calculateur de climatisation',
    'U2003': 'Réveil Commandé à Distance : Incohérence entre signal réveil principal et signal électriqueÛ',
    'U2108': 'Réveil Commandé à Distance : Défaut réception du signal réveil partiel',
    'U2118': 'réveil Commandé à Distance : Défaut réveil partiel valeur reçue incorrecteÊ',
}
