"""
Русские имена параметров чужих блоков (не BSI): двигатель, ABS, блок реле и т.д.

Источник - поле label_korean каталога DiagBox (единственный язык, на котором в
клоне базы есть описания), переведено вручную. Без этого словаря дашборд показывал
пословный автоперевод мнемоник: "Команда relais puissance", "Etatcdedem",
"Состояние app deph aac adm" - владелец французского не знает, и не должен.

Ключ - имя без приставки блока; COMMON покрывает идентификационные поля, которые
у всех блоков одинаковые, BY_FAMILY - измерения конкретного блока. Поиск: сначала
семейство, потом общий словарь, потом ru_labels.humanise как аварийный запас.
"""

COMMON = {
    "ID_80_MP_INDICE_MESS": "Индекс диагностических сообщений",
    "ID_DATE_TELECH": "Дата загрузки ПО",
    "ID_DATE_TELECHARGEMENT": "Дата загрузки ПО",
    "ID_FE_APPLICATION_FE": "Признак применения",
    "ID_MESS_DIAGNOSTIC": "Идентификатор диагностики",
    "ID_NOMBRE_DE_TELECHARGEMENT": "Число загрузок ПО",
    "ID_NOM_DU_FOURNISSEUR": "Поставщик блока",
    "ID_REFERENCE_COMPLEMENTAIRE_MATERIEL": "Доп. номер блока",
    "ID_REFERENCE_FOURNISSEUR": "Номер поставщика",
    "ID_REFERENCE_LOGICIEL": "Номер ПО",
    "ID_REFERENCE_MATERIEL": "Номер блока",
    "ID_REFERENCE_MAT": "Номер блока",
    "ID_REFERENCE_PSA": "Номер PSA",
    "ID_TRACABILITE_DATE_FABRICATION": "Дата изготовления",
    "ID_TRACABILITE_INDICE_EVOLUTION_EDITION": "Версия ПО",
    "ID_TRACABILITE_INDICE_EVOLUTION_EDITION_CALIBRATION": "Версия калибровки",
    "ID_TRACABILITE_NUMERO_DE_SERIE_PIECE": "Серийный номер",
    "ID_TRACABILITE_CONTROLE_FOURNISSEUR": "Контроль поставщика",
    "ID_TRACABILITE_INTERVENTION_APRES_VENTE": "Число сервисных вмешательств",
    "ID_VERSION_LOGICIEL": "Версия ПО",
    "ID_VERSION_LOGICIEL_new_1": "Версия ПО",
    "ID_VERSION_LOGICIEL_new_4": "Версия ПО",
    "ID_VERSION_DU_LOGICIEL": "Версия ПО",
    "ID_EDITION_LOGICIEL": "Редакция ПО",
    "ID_EDI_CALIB": "Редакция калибровки",
    "ID_VERSION_DIAGNOSTIC": "Версия диагностики",
    "ID_ZI_CODE_SYSTEME": "Код системы",
    "ID_ZI_FILE": "Номер файла калибровки",
    "MP_VITESSE_VEHICULE_a": "Скорость автомобиля",
}

BY_FAMILY = {
    "V46_32": {
        "MP_ANGLE_PAPILLON_CONSIGNE": "Заданный угол дроссельной заслонки",
        "MP_ANGLE_PAPILLON_MESURE": "Измеренный угол дроссельной заслонки",
        "MP_APPRENTISSAGE_BUTE_MINI_PAPILLON_PISTE_01": "Обучение нижнего упора дросселя, дорожка 1",
        "MP_APPRENTISSAGE_BUTE_MINI_PAPILLON_PISTE_02": "Обучение нижнего упора дросселя, дорожка 2",
        "MP_APP_POS_MAXI_PEDALE_1": "Обучение педали газа: максимум, дорожка 1",
        "MP_APP_POS_MAXI_PEDALE_2": "Обучение педали газа: максимум, дорожка 2",
        "MP_APP_POS_MINI_PEDALE_1": "Обучение педали газа: минимум, дорожка 1",
        "MP_APP_POS_MINI_PEDALE_2": "Обучение педали газа: минимум, дорожка 2",
        "MP_AUTORISATION_DEMARRAGE_CALCULATEURS_BV": "Разрешение пуска от блока КПП",
        "MP_AVANCE_ALLUMAGE_APPLIQUEE_A_CHAQUE_CYLINDRE": "Угол опережения зажигания",
        "MP_AVANCE_ALLUMAGE_MAXIMUM": "Максимальный угол опережения",
        "MP_AVANCE_ALLUMAGE_MINIMUM": "Минимальный угол опережения",
        "MP_AVANCE_ALLUMAGE_OPTIMAL": "Оптимальный угол опережения",
        "MP_BESOIN_APPRENTISSAGE_BUTEES_PAPILLON": "Требуется обучение упоров дросселя",
        "MP_BRUIT_CAPTEUR_CLIQUETIS": "Шум по датчику детонации",
        "MP_CDERCOELECPURGE": "Продувка адсорбера, скважность клапана",
        "MP_CHARGE_ESTIMEE_CANISTER": "Насыщение адсорбера (оценка)",
        "MP_COMMANDE_RELAIS_PUISSANCE": "Команда силового реле",
        "MP_COMPTDEMMOT": "Счётчик пусков двигателя",
        "MP_COMPTEUR_NB_DEMARRAGE_A_FROID": "Счётчик холодных пусков",
        "MP_CONSIGNE_POSITION_DEPHASEUR_AAC_ADMISSION": "Заданное положение фазовращателя впуска",
        "MP_CONSIGNE_PRESSION_ADMISSION": "Заданное давление во впуске",
        "MP_CONSIGNE_VITESSE_GMV_C5": "Задание скорости вентилятора",
        "MP_CON_RICHESSE": "Заданный состав смеси",
        "MP_COUPLE_MOTEUR_AVANCE": "Момент двигателя по опережению (факт)",
        "MP_COUPLE_MOTEUR_EFFECTIF_AIR": "Момент двигателя по воздуху (задание)",
        "MP_COUPLE_MOTEUR_EFFECTIF_AVANCE": "Эффективный момент по опережению",
        "MP_COUPLE_RESISTANT_MOTEUR_ESTIME": "Момент сопротивления (оценка)",
        "MP_COUPLE_VOLONTE_CONDUCTEUR": "Момент, запрошенный водителем",
        "MP_DEBAIRCONS": "Требуемый расход воздуха",
        "MP_DEBIT_AIR": "Расход воздуха",
        "MP_DEPASSEMENT_SEUIL_ENCRASSEMENT_MOTEUR": "Превышен порог закоксовывания",
        "MP_ESTIMATION_PUISSANCE_CONSO_COMPRESSEUR_REFRI": "Мощность, отбираемая компрессором кондиционера",
        "MP_ETATCDEDEM": "Состояние команды стартера",
        "MP_ETAT_APP_BUTEES_PAPILLON_MOTORISE": "Обучение упоров дросселя: состояние",
        "MP_ETAT_APP_DEPH_AAC_ADM": "Обучение фазовращателя впуска: состояние",
        "MP_ETAT_COH_POSITION_AAC_ADMI_VIL": "Согласованность впускного вала и коленвала",
        "MP_ETAT_CONTACTEUR_PEDALE_FREIN": "Выключатель педали тормоза",
        "MP_ETAT_FONCTIONNEMENT_MOTEUR_THERMIQUE": "Режим работы двигателя",
        "MP_ETAT_GMP": "Состояние силового агрегата",
        "MP_ETAT_GMV_PTIT_C5": "Реле вентилятора, малая скорость",
        "MP_ETAT_LVV": "Ограничитель скорости: состояние",
        "MP_ETAT_MTH": "Состояние двигателя",
        "MP_ETAT_PROGRAMMATION_ANTI_DEMARRAGE": "Иммобилайзер: состояние программирования",
        "MP_ETAT_REGULATION_SONDE_A_OXYGENE_AMONT": "Регулирование по лямбде до катализатора",
        "MP_ETAT_REGULATION_SONDE_A_OXYGENE_AVAL": "Регулирование по лямбде после катализатора",
        "MP_ETAT_RELAIS_GMV": "Реле вентилятора охлаждения",
        "MP_ETAT_REL_GMV_C5": "Реле вентилятора, большая скорость",
        "MP_ETAT_REVEIL_CALCULATEUR": "Пробуждение ЭБУ: состояние",
        "MP_ETAT_RVV": "Круиз-контроль: состояние",
        "MP_ETAT_SONDE_A_OXYGENE_AMONT": "Лямбда до катализатора: состояние",
        "MP_ETAT_SONDE_A_OXYGENE_AVAL": "Лямбда после катализатора: состояние",
        "MP_ETAT_VERROUILLAGE_DEVERROUILLAGE_CALCULTATEUR": "Блокировка ЭБУ: состояние",
        "MP_FACTEUR_CORRECTION_RICHESSE_AMONT": "Коррекция смеси по лямбде до кат.",
        "MP_FACTEUR_CORRECTION_RICHESSE_AVAL": "Коррекция смеси по лямбде после кат.",
        "MP_INFORMATION_CAPTEUR_EMBRAYAGE": "Датчик сцепления",
        "MP_INFORMATION_POINT_DUR_PEDALE_ACCELERATEUR": "Педаль газа: точка сопротивления",
        "MP_INFO_DETECTION_CHOC": "Обнаружен удар",
        "MP_NIVEAU_CARBURANT_AFFICHE": "Уровень топлива (по ЭБУ)",
        "MP_OPTION_APPAIRAGE_CHOISIE": "Выбранный вариант сопряжения",
        "MP_PB_TRANSMISSION_CODE_DEVERROUILLAGE": "Сбой передачи кода разблокировки",
        "MP_PEDALE_ACCELERATEUR_1": "Педаль газа, датчик 1, напряжение",
        "MP_PEDALE_ACCELERATEUR_2": "Педаль газа, датчик 2, напряжение",
        "MP_POSITION_PEDALE_EMBRAYAGE": "Положение педали сцепления",
        "MP_POSPEDACC1": "Положение педали газа, дорожка 1",
        "MP_POSPEDACC2": "Положение педали газа, дорожка 2",
        "MP_POS_DEPHASEUR_ACC_1": "Положение фазовращателя впуска",
        "MP_PRESSIONTUBULURE": "Давление во впускном коллекторе",
        "MP_PRESSION_ATMOSPHERIQUE": "Атмосферное давление",
        "MP_PRESSION_CIRCUIT_REFRIGERANT_a": "Давление хладагента кондиционера",
        "MP_PRESSION_HUILE_MOTEUR": "Давление масла",
        "MP_PRESSION_MASTERVAC": "Разрежение в вакуумном усилителе",
        "MP_RAPPORT_ENGAGE": "Включённая передача",
        "MP_RCOAMONT": "Подогрев лямбды до кат., скважность",
        "MP_RCOAVAL": "Подогрев лямбды после кат., скважность",
        "MP_RCO_ELECTROVANNE_DEPHASEUR_ACC_1": "Клапан фазовращателя впуска, скважность",
        "MP_REGIME_MOTEUR": "Обороты двигателя",
        "MP_REGMOTRALENTI": "Заданные обороты холостого хода",
        "MP_REMPLISSAGE_DE_CONSIGNE": "Заданное наполнение цилиндров",
        "MP_REMPLISSAGE_MESURE": "Измеренное наполнение цилиндров",
        "MP_RETRAIT_AVANCE_ALLUMAGE_CYLINDRE_01": "Снижение опережения, цилиндр 1",
        "MP_RETRAIT_AVANCE_ALLUMAGE_CYLINDRE_02": "Снижение опережения, цилиндр 2",
        "MP_RETRAIT_AVANCE_ALLUMAGE_CYLINDRE_03": "Снижение опережения, цилиндр 3",
        "MP_RETRAIT_AVANCE_ALLUMAGE_CYLINDRE_04": "Снижение опережения, цилиндр 4",
        "MP_STATUS_PREMIER_APP_DEPH_AAC_ADM": "Первое обучение фазовращателя: состояние",
        "MP_TEMPERATURE_AIR_EXTERIEUR": "Температура наружного воздуха",
        "MP_TEMPERATURE_D_EAU_MOTEUR_d": "Температура охлаждающей жидкости",
        "MP_TEMPERATURE_EAU_DERNIER_ARRET_MOTEUR": "Температура ОЖ при последней остановке",
        "MP_TEMPS_ARRET_MOTEUR": "Время с остановки двигателя",
        "MP_TEMPS_INJECTION_CYLINDRE_01": "Время впрыска, цилиндр 1",
        "MP_TEMPS_INJECTION_CYLINDRE_02": "Время впрыска, цилиндр 2",
        "MP_TEMPS_INJECTION_CYLINDRE_03": "Время впрыска, цилиндр 3",
        "MP_TEMPS_INJECTION_CYLINDRE_04": "Время впрыска, цилиндр 4",
        "MP_TEMP_AIR_ADMISSION_SUP": "Температура воздуха на впуске",
        "MP_TENSION_ALIMENTATION_CALCULATEUR_CONTROLE_MOTEUR": "Питание ЭБУ двигателя",
        "MP_TENSION_ALIMENTATION_CAPTEURS_01": "Питание датчиков, шина 1",
        "MP_TENSION_ALIMENTATION_CAPTEURS_02": "Питание датчиков, шина 2",
        "MP_TENSION_ALIMENTATION_CAPTEURS_03": "Питание датчиков, шина 3",
        "MP_TENSION_RECOPIE_POSITION_PAPILLON_01": "Датчик положения дросселя 1, напряжение",
        "MP_TENSION_RECOPIE_POSITION_PAPILLON_02": "Датчик положения дросселя 2, напряжение",
        "MP_TENSION_SONDE_A_OXYGENE_AMONT": "Лямбда до катализатора, напряжение",
        "MP_TENSION_SONDE_A_OXYGENE_AVAL": "Лямбда после катализатора, напряжение",
        "MP_TYPE_BOITE_VITESSES": "Тип коробки передач",
        "MP_VALEUR_APPRENTISSAGE_BUTEE_BASSE_DEPHASEUR_AAC_ADMISSION": "Обучение нижнего упора фазовращателя",
        "MP_VALEUR_APP_LIMP_HOME_BPM_SIGNAL_1": "Аварийное положение дросселя, сигнал 1",
        "MP_VALEUR_APP_LIMP_HOME_BPM_SIGNAL_2": "Аварийное положение дросселя, сигнал 2",
        "MP_VITESSE_CONSIGNE_LIMITATION_DE_VITESSE": "Заданная скорость ограничителя",
        "CONFIG_INDICE_TELECODAGE": "Индекс телекодирования",
    },
    "BSM_2010": {
        "MP_ACQUISITION_COMMANDE_RELAIS_PRINCIPAL": "Главное реле: команда получена",
        "MP_ACQUISITION_COMMANDE_RELAIS_PUISSANCE": "Силовое реле: команда получена",
        "MP_ALERTE_NIVEAU_EAU_MOTEUR": "Лампа уровня охлаждающей жидкости",
        "MP_ALERTE_PRESSION_HUILE_MOTEUR_a": "Лампа давления масла",
        "MP_COMMANDE_AVER_SONORE": "Звуковой сигнал",
        "MP_COMMANDE_DEMARREUR": "Команда стартера",
        "MP_COMMANDE_ESSUIE_VITRE_AV_GV": "Дворники, быстрая скорость",
        "MP_COMMANDE_ESSUIE_VITRE_AV_PV": "Дворники, медленная скорость",
        "MP_COMMANDE_FEU_CROISEMENT_D": "Ближний свет, правый (команда)",
        "MP_COMMANDE_FEU_CROISEMENT_G": "Ближний свет, левый (команда)",
        "MP_COMMANDE_FEU_DIURNE_DEDIE_D": "Дневные огни, правый (ШИМ)",
        "MP_COMMANDE_FEU_DIURNE_DEDIE_G": "Дневные огни, левый (ШИМ)",
        "MP_COMMANDE_FEU_ROUTE_D": "Дальний свет, правый (команда)",
        "MP_COMMANDE_FEU_ROUTE_G": "Дальний свет, левый (команда)",
        "MP_COMMANDE_FEU_STATIQUE_D": "Статическая подсветка поворота, правая",
        "MP_COMMANDE_FEU_STATIQUE_G": "Статическая подсветка поворота, левая",
        "MP_COMMANDE_LAVAGE_AR": "Омыватель заднего стекла",
        "MP_COMMANDE_LAVAGE_AV": "Омыватель лобового стекла",
        "MP_COMMANDE_LAVAGE_PROJECTEURS": "Омыватель фар",
        "MP_COMMANDE_OCCULTANT_D": "Шторка фары, правая",
        "MP_COMMANDE_OCCULTANT_G": "Шторка фары, левая",
        "MP_COMMANDE_PWM_ANTIBROUILLARD_AVD": "Противотуманная фара, правая (ШИМ)",
        "MP_COMMANDE_PWM_ANTIBROUILLARD_AVG": "Противотуманная фара, левая (ШИМ)",
        "MP_COMMANDE_RELAIS_POMPE_AIR": "Реле воздушного насоса",
        "MP_COMMANDE_RELAIS_PUISSANCE": "Команда силового реле",
        "MP_DEMANDE_DEMARRAGE_BSI": "Запрос пуска от BSI",
        "MP_EMBR_COMPR_CLIM": "Муфта компрессора кондиционера",
        "MP_EMBR_COMPR_CLIM_P": "Муфта компрессора кондиционера (силовая)",
        "MP_ETAT_INHIBITION_SORTIE_ECLAIRAGE_VIRAGE_STATIQUE_DROIT": "Выход подсветки поворота, правый",
        "MP_ETAT_INHIBITION_SORTIE_ECLAIRAGE_VIRAGE_STATIQUE_GAUCHE": "Выход подсветки поворота, левый",
        "MP_ETAT_RECHAUFFEUR": "Дополнительный подогреватель",
        "MP_ETAT_RELAIS_PLUS_APC": "Реле +12 В после замка зажигания",
        "MP_ETAT_RELAIS_PRINCIPAL": "Главное реле",
        "MP_ETAT_REVEIL_CMD_DISTANCE": "Пробуждение от брелока",
        "MP_ETAT_SORTIE_CONFIGURABLE": "Настраиваемый выход",
        "MP_INFO_DEMANDE_DEMARRAGE_CMM": "Запрос пуска к ЭБУ двигателя",
        "MP_INFO_EXCITATION_ALTERNATEUR": "Возбуждение генератора (признак)",
        "MP_INFO_MARCHE_AR": "Задний ход",
        "MP_INFO_PRESENCE_EAU_GAZOLE": "Вода в топливе (дизель)",
        "MP_INHIB_BROUILLARD_AVD": "Питание противотуманной фары, правая",
        "MP_INHIB_BROUILLARD_AVG": "Питание противотуманной фары, левая",
        "MP_INHIB_CROISEMENT_D": "Выход ближнего света, правый",
        "MP_INHIB_CROISEMENT_G": "Выход ближнего света, левый",
        "MP_INHIB_DIURNE_DEDIE_D": "Выход дневных огней, правый",
        "MP_INHIB_DIURNE_DEDIE_G": "Выход дневных огней, левый",
        "MP_MOTEUR_LEVEE_SOUPAPE_VARIABLE": "Мотор изменения подъёма клапанов",
        "MP_NIVEAU_LIQUIDE_LAVE_GLACE": "Омывайка на исходе",
        "MP_POMPE_AIR": "Воздушный насос",
        "MP_POMPE_AIR1": "Воздушный насос 1",
        "MP_POS_ARRET_FIXE_AV": "Дворники в парковочном положении",
        "MP_RECHAUFFEUR_GAZOLE_VAPEURS_HUILE": "Подогрев топлива / паров масла",
        "MP_REL_APC_BARRE": "Питание после замка зажигания",
        "MP_TENSION_CAPTEUR_NIVEAU_HUILE_MOTEUR": "Датчик уровня масла, напряжение",
        "MP_TENSION_EXCITATION_ALTERNATEUR": "Возбуждение генератора",
        "MP_VANNE_COMPR_CLIM": "Клапан компрессора кондиционера, скважность",
    },
    "ESP81": {
        "MP_CONTACTEUR_FEUX_STOP1": "Выключатель стоп-сигналов",
        "MP_ETAT_RELAIS_ALIMENTATION_EV": "Реле питания клапанов ABS",
        "MP_ETAT_RELAIS_POMPE_RECIRCULATION_1": "Реле насоса ABS",
        "MP_NIVEAU_LIQUIDE_DE_FREIN": "Тормозная жидкость ниже минимума",
        "MP_VITESSE_VEHICULE_a": "Скорость автомобиля (по ABS)",
        "MP_VITESSE_ROUE_ARRIERE_DROITE": "Скорость колеса, заднее правое",
        "MP_VITESSE_ROUE_ARRIERE_GAUCHE": "Скорость колеса, заднее левое",
        "MP_VITESSE_ROUE_AVANT_DROIT": "Скорость колеса, переднее правое",
        "MP_VITESSE_ROUE_AVANT_GAUCHE": "Скорость колеса, переднее левое",
    },
    "GEP": {
        "APC": "Зажигание включено",
        "CFG____ASSISTANCE_1": "Состояние усилителя руля",
        "INTENSITE_MESUREE": "Ток электронасоса ГУР",
        "MP_ETAT_MOTEUR_THERMIQUE_1_2": "Состояние двигателя (по насосу)",
        "MP_TEMPERATURE_GEP": "Температура электронасоса ГУР",
        "MP_TENSION_ALIMENTATION": "Питание электронасоса ГУР",
        "MP_VITESSE_MOTEUR_GEP": "Обороты электронасоса ГУР",
        "MP_VITESSE_VOLANT_DE_DIRECTION": "Скорость вращения руля",
        "MP_VITESSE_VEHICULE_a": "Скорость автомобиля (по насосу ГУР)",
        "TYPE_ANGLE_VOLANT_DE_DIRECTION": "Тип датчика угла руля",
    },
    "RBG_UDS": {
        "ID_REF_COMP_MATERIEL_SAT_PIED_MILIEU_D": "Датчик бокового удара, правый: доп. номер",
        "ID_REF_COMP_MATERIEL_SAT_PIED_MILIEU_G": "Датчик бокового удара, левый: доп. номер",
        "ID_VERSION_HARD_SAT_PIED_MILIEU_D": "Датчик бокового удара, правый: версия",
        "ID_VERSION_HARD_SAT_PIED_MILIEU_G": "Датчик бокового удара, левый: версия",
        "MP_COMPTEUR_DE_CHOCS": "Счётчик срабатываний подушек",
        "MP_ETAT_COMMUTATEUR_NEUTRALISATION_COUSSIN_PASSAGER": "Выключатель подушки пассажира",
        "MP_ETAT_COUSSIN_CONDUCTEUR_NIVEAU_1": "Подушка водителя: состояние",
        "MP_ETAT_COUSSIN_LATERAL_AVANT_DROIT": "Боковая подушка, правая: состояние",
        "MP_ETAT_COUSSIN_LATERAL_AVANT_GAUCHE": "Боковая подушка, левая: состояние",
        "MP_ETAT_COUSSIN_LATERAL_TETE_AVANT_DROIT": "Боковая подушка головы, правая: состояние",
        "MP_ETAT_COUSSIN_PASSAGER_NIVEAU_1": "Подушка пассажира: состояние",
        "MP_ETAT_COUSSIN_RIDEAU_DROIT": "Шторка безопасности, правая: состояние",
        "MP_ETAT_COUSSIN_RIDEAU_GAUCHE": "Шторка безопасности, левая: состояние",
        "MP_ETAT_PRETENSIONNEUR_AVANT_DROIT": "Преднатяжитель, правый: состояние",
        "MP_ETAT_PRETENSIONNEUR_AVANT_GAUCHE": "Преднатяжитель, левый: состояние",
        "MP_ETAT_VERROUILLAGE_APV_ECU_RBG": "Сервисная блокировка блока подушек",
        "MP_ETAT_VERROUILLAGE_DEFINITIF_ECU_RBG": "Окончательная блокировка блока подушек",
        "MP_ID_FOURNISSEUR_SAT_PIED_MILIEU_D": "Датчик бокового удара, правый: поставщик",
        "MP_ID_FOURNISSEUR_SAT_PIED_MILIEU_G": "Датчик бокового удара, левый: поставщик",
        "MP_RESISTANCE_COMMUTATEUR_NEUTRALISATION_COUSSIN_PASSAGER": "Цепь выключателя подушки пассажира, Ом",
        "MP_RESISTANCE_LIGNE_COUSSIN_CONDUCTEUR_NIVEAU_1": "Цепь подушки водителя, Ом",
        "MP_RESISTANCE_LIGNE_COUSSIN_LATERAL_AVANT_DROIT": "Цепь боковой подушки, правая, Ом",
        "MP_RESISTANCE_LIGNE_COUSSIN_LATERAL_AVANT_GAUCHE": "Цепь боковой подушки, левая, Ом",
        "MP_RESISTANCE_LIGNE_COUSSIN_PASSAGER_NIVEAU_1": "Цепь подушки пассажира, Ом",
        "MP_RESISTANCE_LIGNE_PRETENSIONNEUR_AVANT_DROIT": "Цепь преднатяжителя, правая, Ом",
        "MP_RESISTANCE_LIGNE_PRETENSIONNEUR_AVANT_GAUCHE": "Цепь преднатяжителя, левая, Ом",
    },
    "COM2008P": {
        "MP_AVERTISSEUR_SONORE": "Звуковой сигнал",
        "MP_COMMANDE_CLIGNOTANTS": "Указатели поворота",
        "MP_COMMANDE_ESSUYAGE_IMPULSIONNELLE_AVANT": "Однократный взмах дворников",
        "MP_COMMANDE_ESSUYAGE_LUNETTE_ARRIERE": "Задний дворник",
        "MP_COMMANDE_ESSUYAGE_PARE_BRISE": "Передние дворники",
        "MP_COMMANDE_FEUX_ANTIBROUILLARD": "Противотуманные фары",
        "MP_COMMANDE_IMPULSIONNELLE_FEUX_DE_ROUTE": "Мигание дальним",
        "MP_COMMANDE_INVERSEUR_FEUX_DE_CROISEMENT_FEUX_DE_ROUTE": "Переключатель ближний/дальний",
        "MP_COMMANDE_LAVAGE_PARE_BRISE": "Омыватель лобового стекла",
        "MP_DEMANDE_LAVAGE_LUNETTE": "Омыватель заднего стекла",
        "MP_ETAT_COMMANDE_ECLAIRAGE_COMMUTATEUR_3_POSITIONS": "Кольцо света, 3 положения",
        "MP_ETAT_COMMANDE_ECLAIRAGE_COMMUTATEUR_4_POSITIONS": "Кольцо света, 4 положения",
        "MP_PRESENCE_CLE": "Ключ в замке",
        "MP_PUSH_COMMANDE_ECLAIRAGE": "Кнопка на торце рычага света",
        "MP_PUSH_COMMANDE_ESSUYAGE": "Кнопка на торце рычага дворников",
        "MP_SYNCHRO_CLE": "Синхронизация ключа",
    },
    "COMBINE_UDS": {
        "MP_COMMUTATEUR_AIDE_STATIONNEMENT": "Кнопка парктроника",
        "MP_COMMUTATEUR_CHANGE_COULEUR_COURONNE": "Кнопка цвета подсветки шкал",
        "MP_COMMUTATEUR_CHANGE_COULEUR_LCD": "Кнопка цвета экрана",
        "MP_COMMUTATEUR_CHECK_RAZ_ODOMETRE": "Кнопка сброса суточного пробега",
        "MP_COMMUTATEUR_ESP": "Кнопка ESP",
        "MP_COMMUTATEUR_REGLAGE_LUMINOSITE": "Кнопка яркости подсветки",
        "MP_COMMUTATEUR_SAM": "Кнопка контроля слепых зон",
        "MP_COMMUTATEUR_SYSTEME_ALERTE_FRANCH_INVOL_LIGNE": "Кнопка контроля полосы",
        "MP_PRESENCE_MONTRE": "Часы в щитке",
    },
    "AAS_UDS": {
        "MP_ETAT_AAS_ARRIERE": "Парктроник задний: состояние",
        "MP_ETAT_AAS_AV": "Парктроник передний: состояние",
        "MP_ETAT_PUSH_INHIBITION": "Кнопка отключения парктроника",
        "MP_ETAT_SYSTEME_MPD": "Измерение места для парковки: состояние",
        "MP_LONGUEUR_PLACE_MESUREE": "Длина измеренного места",
        "MP_PRESENCE_REMORQUE": "Прицеп подключён",
        "MP_VOYANT_INHIB_AAS": "Парктроник отключён (лампа BSI)",
    },
    "CDPL_UDS_HELLA": {
        "MP_ETAT_ESSUYAGE": "Дворники: состояние",
        "MP_LUM_AMBI": "Освещённость вокруг",
        "MP_LUM_FRONT": "Освещённость спереди",
        "MP_VITESSE_BALAYAGE": "Скорость дворников",
        "MP_VOLUME_PLUIE_MESUREE_CELLULE_1": "Датчик дождя, ячейка 1",
        "MP_VOLUME_PLUIE_MESUREE_CELLULE_2": "Датчик дождя, ячейка 2",
        "MP_VOLUME_PLUIE_MESUREE_CELLULE_3": "Датчик дождя, ячейка 3",
    },
    "BPGA2010": {
        "MP_COMMANDE_RELAIS_CPC": "Реле питания CPC: команда",
        "MP_DEMANDE_MISE_CONTACT": "Запрос включения зажигания",
        "MP_ETAT_RELAIS_CPC": "Реле питания CPC: состояние",
        "MP_ETAT_RELAIS_PRINCIPAL_CMM": "Главное реле ЭБУ двигателя",
    },
    "FMUX": {
        "MP_DEMANDE_AIR_CONDITIONNE_TOUCHE_AC": "Кнопка A/C",
        "MP_DEMANDE_DE_REGULATION_AUTOMATIQUE": "Кнопка AUTO климата",
        "MP_MOLETTE_VOLUME": "Регулятор громкости",
        "MP_TOUCHE_DEGIVRAGE_DESEMBUAGE_AVANT": "Кнопка обдува лобового стекла",
    },
}


def label(full_name: str):
    """Русское имя для 'СЕМЕЙСТВО:МНЕМОНИКА' или None, если не знаем."""
    if ":" not in full_name:
        return None
    fam, mn = full_name.split(":", 1)
    return BY_FAMILY.get(fam, {}).get(mn) or COMMON.get(mn)
